name: Environment test and sec and var2

on: [push, workflow_dispatch]
jobs:
  using_bash_diff_enviroment:
    runs-on: ubuntu-latest
    environment: dev

    env:
      GLOBAL_VAR: 'This is a global variable'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "Global Variable: $GLOBAL_VAR"
          echo "Job Variable: $JOB_VAR"
          echo "Node Environment: $NODE_ENV"

      - name: Set and print job-specific variable
        run: |
          JOB_VAR='This is a job-specific variable'
          NODE_ENV='production'
          echo "Job Variable: $JOB_VAR"
          echo "Node Environment: $NODE_ENV"

      - name: Use secret
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
          SECRET_USERNAME: ${{ secrets.SECRET_USERNAME }}
        run: |
          echo "Using secret API key: $SECRET_API_KEY"
          echo "Using secret USERNAME: $SECRET_USERNAME"
